language: java
sudo: required
jdk:
 - oraclejdk8
matrix:
  fast_finish: true
install: true
before_script:
  - chmod +x travis/deploy.sh
  - chmod +x travis/checkForTag.sh
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${MY_GH_TOKEN_OXYGEN}:@github.com" > .git/credentials
  - ./travis/checkForTag.sh
script:
 - mvn clean install
before_deploy:
  - ./travis/deploy.sh
deploy:
  provider: releases
  api_key: ${MY_GH_TOKEN_OXYGEN}
  file:
    - target/git.support-${TRAVIS_TAG}-plugin.jar
    - target/addon.xml
  skip_cleanup: true
  on:
    tags: true
